# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_version=3.0.0
maven_group=dev.trinsdar
archive_base_name=BearCore

# Minecraft
minecraft_version=1.19.2
mappings_version=2022.11.27
mod_name=BearCore
mod_author=Trinsdar, Bear989, Speiger
mod_id=bearcore
license=Apache 2.0
credits=Speiger for originally making the mod
description=A mod that limits sleeping to only a short bit at any time of day and stops bonemealing of crops
minecraft_version_range=[1.18.2,)

# Forge
forge_version=43.5.0
forge_loader_version_range=[40,)
forge_version_range=[40,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
